wandb_version: 1

learning-rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: yolact_resnet50
dataset:
  desc: null
  value: trial-subset
iterations:
  desc: null
  value: 500
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699740011.637777
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.2
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
